# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JanrainPodDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod 'libextobjc/EXTScope', '~>0.4'
    pod 'GTMAppAuth' #Pods for Google Login (Google Drive App OAuth)
    pod 'AppAuth'
    pod 'Janrain', :git => 'https://github.com/janrain/jump.ios.git', :tag => '5.0.3'    

end